# sonar-project.properties
sonar.organization=wissal2023
sonar.projectKey=wissal2023_DevOps_test
sonar.projectName=Global Leaders Trade - Frontend

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*.test.jsx,**/*.spec.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8